// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8dxoyOWswhN7x132xPoYXNDQegJ0nBVs',
    appId: '1:358285087395:android:d3cdd90bda57c0eb2b2516',
    messagingSenderId: '358285087395',
    projectId: 'fooddeliveryapp-65851',
    databaseURL: 'https://fooddeliveryapp-65851-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddeliveryapp-65851.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGyt51YuBIelrgaDG4QOS3KvsVz1Dvsi8',
    appId: '1:358285087395:ios:738ad23383d9beaf2b2516',
    messagingSenderId: '358285087395',
    projectId: 'fooddeliveryapp-65851',
    databaseURL: 'https://fooddeliveryapp-65851-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fooddeliveryapp-65851.appspot.com',
    androidClientId: '358285087395-98bqfc9sfss1h1cjv18sdnmeoihq1dt2.apps.googleusercontent.com',
    iosClientId: '358285087395-k922eb2bgve35ldobhiembv5pia6ufc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.quickEatsApp',
  );
}
